# .travis.yml
language: node_js
node_js:
  - '8'
branches:
  only:
    - master
cache:
  yarn: true
script:
  - git config --global user.name "${GH_NAME}"
  - git config --global user.email "${GH_EMAIL}"
  - echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc
  # install Docusaurus and generate english strings file
  #- cd website && yarn install && yarn write-translations && cd ..
  # install Crowdin
  # build and publish website
  - cd website && yarn install && GIT_USER="${GH_NAME}" yarn run publish-gh-pages